#!/bin/bash
# WP LOA Automation - Quick Start

echo "=================================="
echo "WP LOA Report Automation - v1.0"
echo "=================================="
echo ""
echo "QUICK START GUIDE"
echo ""
echo "Option 1: GUI Application"
echo "  $ python app_desktop.py"
echo "  → Click 'WP LOA Report' tab"
echo "  → Select files and process"
echo ""
echo "Option 2: Command Line Testing"
echo "  1. Place your WP LOA file in 'uploads' folder"
echo "     $ cp your_file.xlsx uploads/"
echo ""
echo "  2. Process the file:"
echo "     $ python test_wp_loa.py"
echo ""
echo "  3. Check output in 'uploads' folder"
echo "     → output_your_file.xlsx"
echo ""
echo "Option 3: Diagnose VLOOKUP Issues"
echo "  If VLOOKUP shows 'N/A', run:"
echo "     $ python test_wp_loa.py analyze"
echo ""
echo "  This will show BUDGET sheet structure"
echo "  so we can fix the column mappings"
echo ""
echo "EXPECTED RESULTS"
echo "==============="
echo "✓ Row 1: Headers in columns K-AA"
echo "✓ Rows 2+: Formulas (not values)"
echo "✓ Column O: L1 formula: =L&\"-\"&M&\"-\"&N"
echo "✓ Column Q-AA: VLOOKUP formulas to BUDGET"
echo ""
echo "TROUBLESHOOTING"
echo "==============="
echo "No BUDGET sheet?"
echo "  → Create internal 'BUDGET' worksheet"
echo "  → Column A: L1 WBS codes"
echo "  → Column B onwards: Data columns"
echo ""
echo "VLOOKUP returning 'N/A'?"
echo "  → Run: python test_wp_loa.py analyze"
echo "  → Check BUDGET sheet column structure"
echo "  → Adjust column numbers in wp_loa_formula.py"
echo ""
echo "More details: See WP_LOA_AUTOMATION_GUIDE.md"
echo ""
