#!/usr/bin/env python
"""
Verify the external file lookup formulas
"""

print('✅ EXTERNAL FILE LOOKUP FORMULAS')
print('=' * 120)
print()

print('Column W (PROPONENT) - Lookup to LOA_CURRENT_APPROVER workbook:')
print('-' * 120)
print('Source File: LOA_CURRENT_APPROVER (Auto Email).xlsx')
print('Sheet: page')
print('Lookup Key: Column A (from WP LOA REPORT)')
print('Lookup Range: $A:$I')
print('Return Column: 9 (Reported By)')
print('Formula: =IFERROR(PROPER(VLOOKUP(A{row},\'[LOA_CURRENT_APPROVER (Auto Email).xlsx]page\'!$A:$I,9,0)),"N/A")')
print('Purpose: Get the approver/reporter name from LOA workbook')
print()

print('Column X (PROPONENT 1) - Format PROPONENT name:')
print('-' * 120)
print('Source: Column W (PROPONENT)')
print('Transform: "Last, First" → "First Last"')
print('Example: "Salvador, Luis" → "Luis Salvador"')
print('Formula: =IFERROR(PROPER(TRIM(MID(W{row},FIND(",",W{row})+2,LEN(W{row}))&" "&LEFT(W{row},FIND(",",W{row})-1))),"N/A")')
print('Purpose: Reformat the PROPONENT name to First Name Last Name order')
print()

print('Column Y (DIV IN REPORT) - Lookup to 2026 CAPEX AVAILMENT workbook:')
print('-' * 120)
print('Source File: 2026 CAPEX AVAILMENT_as of Feb 16.xlsx')
print('Sheet: data_2026')
print('Lookup Key: Column R (DIV code - SPE, NTG, etc. from BUDGET lookup)')
print('Lookup Range: $A:$H')
print('Return Column: 8 (Division column)')
print('Formula: =IFERROR(VLOOKUP(R{row},\'[2026 CAPEX AVAILMENT_as of Feb 16.xlsx]data_2026\'!$A:$H,8,0),"N/A")')
print('Purpose: Get the Division information from the 2026 CAPEX AVAILMENT data')
print()

print('=' * 120)
print()
print('📝 IMPORTANT NOTES:')
print()
print('1. **File Path References:**')
print('   - Make sure Excel files are in the expected locations (Downloads folder)')
print('   - File names must match EXACTLY (including spaces and special characters)')
print()
print('2. **Lookup Keys:**')
print('   - PROPONENT: Looks up the value from Column A (WP LOA number)')
print('   - DIV IN REPORT: Looks up the value from Column R (DIV code)')
print()
print('3. **Error Handling:**')
print('   - All formulas wrapped in IFERROR() to show "N/A" if lookup fails')
print('   - This helps identify if files/sheets not found or values don\'t match')
print()
print('4. **Verification Needed:**')
print('   - Test with actual data to confirm lookups return correct values')
print('   - If getting "N/A", check:')
print('     a) File exists in correct location')
print('     b) Sheet name is correct (page, data_2026)')
print('     c) Lookup key value exists in external file')
print('     d) Column numbers are correct')
print()
print('=' * 120)
